name: Deploy All Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-remote:
    runs-on: ubuntu-latest
    name: Deploy Remote Worker
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy Remote Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          config: wrangler.remote.jsonc
          command: deploy
          secrets: |
            SUPABASE_SERVICE_ROLE_KEY
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

  deploy-fastmcp:
    runs-on: ubuntu-latest
    name: Deploy FastMCP Worker
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy FastMCP Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          config: wrangler.fastmcp.jsonc
          command: deploy
          secrets: |
            SUPABASE_SERVICE_ROLE_KEY
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

  deploy-chatgpt:
    runs-on: ubuntu-latest
    name: Deploy ChatGPT Worker
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy ChatGPT Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          config: wrangler.chatgpt.jsonc
          command: deploy
          secrets: |
            SUPABASE_SERVICE_ROLE_KEY
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

  deploy-enhanced:
    runs-on: ubuntu-latest
    name: Deploy Enhanced Worker
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy Enhanced Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          config: wrangler.enhanced.jsonc
          command: deploy
          secrets: |
            SUPABASE_SERVICE_ROLE_KEY
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}